server:
  port: 9081
spring:
  application:
    name: client-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: rest-cliente
            client-secret: XKpBubtF0cAo4OUqJ1mgMTYkKGpvzFYG
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8081/realms/master/protocol/openid-connect/token

